[font]
normal = ["MonaspiceNe Nerd Font"]
size = 14

[[font.bold]]
family = "MonaspiceNe Nerd Font"
style = "w500"

[font.features]
"MonaspiceNe Nerd Font" = [
    "-calt",
    "+ss01",
    "+ss02",
    "+ss03",
    "+ss04",
    "+ss05",
    "+ss06",
    "+ss07",
    "+ss08",
    "+ss09",
    "liga",
]
