[font]
normal = ["JetBrainsMono Nerd Font"]
size = 14

[[font.bold]]
family = "JetBrainsMono Nerd Font"
style = "w400"

[font.features]
"JetBrainsMono Nerd Font" = [
    "+calt",
    "+ss01",
    "+ss02",
    "+ss03",
    "+ss04",
    "+ss05",
    "+ss06",
    "+ss07",
    "+ss08",
    "+ss09",
]
